---
- name: SCORED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install cramfs(\s|$)'
    line: install cramfs /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_1
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.1
    - cramfs

- name: SCORED | 1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install freevxfs(\s|$)'
    line: install freevxfs /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_2
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.2
    - freevxfs

- name: SCORED | 1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install jffs2(\s|$)'
    line: install jffs2 /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_3
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.3
    - jffs2

- name: SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install hfs(\s|$)'
    line: install hfs /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_4
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.4
    - hfs

- name: SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install hfsplus(\s|$)'
    line: install hfsplus /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_5
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.5
    - hfsplus

- name: SCORED | 1.1.1.6 | PATCH | Ensure mounting of udf filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: '^(#)?install udf(\s|$)'
    line: install udf /bin/true
    create: yes
  when:
    - ubuntu1604cis_rule_1_1_1_6
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.1.6
    - udf

- name: SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | copy tmp.mount
  copy:
    src: etc/systemd/system/tmp.mount
    dest: /etc/systemd/system/tmp.mount
    owner: root
    group: root
    mode: 420
  when:
    - ubuntu1604cis_rule_1_1_2
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.2

- name: SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | enable and start/restart tmp.mount
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
  when:
    - ubuntu1604cis_rule_1_1_2
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.2

- name: |-
    SCORED | 1.1.2 | PATCH | Ensure noexec option set on /tmp partition
     SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition
     SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition
     | drop custom tmp.mount
  copy:
    src: etc/systemd/system/tmp.mount
    dest: /etc/systemd/system/tmp.mount
    owner: root
    group: root
    mode: 420
  notify: systemd restart tmp.mount
  when:
    - ubuntu1604cis_rule_1_1_2
    - ubuntu1604cis_rule_1_1_3
    - ubuntu1604cis_rule_1_1_4
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.2
    - rule_1.1.3
    - rule_1.1.4

- name: SCORED | 1.1.5 | PATCH | Ensure separate partition exists for /var
  shell: mount | grep "on /var "
  args:
    warn: no
  register: var_mounted
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_5
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.5

- name: SCORED | 1.1.6 | PATCH | Ensure separate partition exists for /var/tmp
  shell: mount | grep "on /var/tmp "
  args:
    warn: no
  register: var_tmp_mounted
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_6
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.6

- name: |-
    SCORED | 1.1.7  | PATCH | Ensure nodev option set on /var/tmp partition
     SCORED | 1.1.8  | PATCH | Ensure nosuid option set on /var/tmp partition
     SCORED | 1.1.9 | PATCH | Ensure noexec option set on /var/tmp partition
  mount:
    name: /var/tmp
    src: '{{ ubuntu1604cis_vartmp[''source''] }}'
    state: mounted
    fstype: '{{ ubuntu1604cis_vartmp[''fstype''] }}'
    opts: '{{ ubuntu1604cis_vartmp[''opts''] }}'
  when:
    - 'ubuntu1604cis_vartmp[''enabled''] == ''yes'''
    - ubuntu1604cis_rule_1_1_7
    - ubuntu1604cis_rule_1_1_8
    - ubuntu1604cis_rule_1_1_9
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.7
    - rule_1.1.8
    - rule_1.1.9

- name: SCORED | 1.1.10 | PATCH | Ensure separate partition exists for /var/log
  shell: mount | grep "on /var/log "
  register: var_log_mounted
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_10
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.10

- name: SCORED | 1.1.11 | PATCH | Ensure separate partition exists for /var/log/audit
  shell: mount | grep "on /var/log/audit "
  register: var_log_audit_mounted
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_11
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.11

- name: SCORED | 1.1.12 | PATCH | Ensure separate partition exists for /home
  shell: mount | grep "on /home "
  register: home_mounted
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_12
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.12

- name: SCORED | 1.1.13 | PATCH | Ensure nodev option set on /home partition
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_1_13
  tags:
    - level1
    - level2
    - patch
    - rule_1.1.13
    - notimplemented

- name: |-
    SCORED | 1.1.14 | PATCH | Ensure nodev option set on /dev/shm partition
     SCORED | 1.1.15 | PATCH | Ensure nosuid option set on /dev/shm partition
     SCORED | 1.1.16 | PATCH | Ensure noexec option set on /dev/shm partition
  mount:
    name: /dev/shm
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: 'defaults,nodev,nosuid,noexec'
  when:
    - ubuntu1604cis_rule_1_1_14
    - ubuntu1604cis_rule_1_1_15
    - ubuntu1604cis_rule_1_1_16
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.14
    - rule_1.1.15
    - rule_1.1.16

- name: NOTSCORED | 1.1.17 | PATCH | Ensure nodev option set on removable media partitions
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_1_17
  tags:
    - level1
    - notscored
    - patch
    - rule_1.1.17
    - notimplemented

- name: NOTSCORED | 1.1.18 | PATCH | Ensure nosuid option set on removable media partitions
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_1_18
  tags:
    - level1
    - notscored
    - patch
    - rule_1.1.18
    - notimplemented

- name: NOTSCORED | 1.1.19 | PATCH | Ensure noexec option set on removable media partitions
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_1_19
  tags:
    - level1
    - notscored
    - patch
    - rule_1.1.19
    - notimplemented

- name: SCORED | 1.1.20 | PATCH | Ensure sticky bit is set on all world-writable directories
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: no
  failed_when: no
  when:
    - ubuntu1604cis_rule_1_1_20
  tags:
    - level1
    - level2
    - patch
    - rule_1.1.20

- name: SCORED | 1.1.21 | PATCH | Disable Automounting
  service:
    name: autofs
    enabled: no
  when:
    - ubuntu1604cis_allow_autofs == false and autofs_service_status.stdout == "loaded"
    - ubuntu1604cis_rule_1_1_21
  tags:
    - level1
    - patch
    - rule_1.1.21

- name: NOTSCORED | 1.2.1 | PATCH | Ensure package manager repositories are configured
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_2_1
  tags:
    - level1
    - notscored
    - patch
    - rule_1.2.1
    - notimplemented

- name: NOTSCORED | 1.2.2 | PATCH | Ensure GPG keys are configured
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_2_2
  tags:
    - level1
    - notscored
    - patch
    - rule_1.2.3
    - notimplemented

- name: SCORED | 1.3.1 | PATCH | Ensure AIDE is installed
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - aide
    - aide-common
  when:
    - ubuntu1604cis_rule_1_3_1
  tags:
    - level1
    - scored
    - aide
    - patch
    - rule_1.3.1

- name: SCORED | 1.3.1 | PATCH | Ensure AIDE is installed
  command: '/usr/sbin/aide --init -B ''database_out=file:/var/lib/aide/aide.db.gz'''
  args:
    creates: /var/lib/aide/aide.db.gz
  changed_when: no
  failed_when: no
  async: 45
  poll: 0
  when:
    - ubuntu1604cis_config_aide
    - ubuntu1604cis_rule_1_3_1
  tags:
    - level1
    - scored
    - aide
    - patch
    - rule_1.3.1

- name: SCORED | 1.3.2 | PATCH | Ensure filesystem integrity is regularly checked
  cron:
    name: Run AIDE integrity check weekly
    cron_file: '{{ ubuntu1604cis_aide_cron[''cron_file''] }}'
    user: '{{ ubuntu1604cis_aide_cron[''cron_user''] }}'
    minute: '{{ ubuntu1604cis_aide_cron[''aide_minute''] | default(''0'') }}'
    hour: '{{ ubuntu1604cis_aide_cron[''aide_hour''] | default(''5'') }}'
    day: '{{ ubuntu1604cis_aide_cron[''aide_day''] | default(''*'') }}'
    month: '{{ ubuntu1604cis_aide_cron[''aide_month''] | default(''*'') }}'
    weekday: '{{ ubuntu1604cis_aide_cron[''aide_weekday''] | default(''*'') }}'
    job: '{{ ubuntu1604cis_aide_cron[''aide_job''] }}'
  when:
    - ubuntu1604cis_rule_1_3_2
  tags:
    - level1
    - scored
    - aide
    - file_integrity
    - patch
    - rule_1.3.2

- name: SCORED | 1.4.1 | PATCH | Ensure permissions on bootloader config are configured
  stat:
    path: /boot/grub/grub.cfg
  register: grub_cfg
  when:
    - ubuntu1604cis_rule_1_4_1
  tags:
    - level1
    - scored
    - grub
    - patch
    - rule_1.4.1

- name: SCORED | 1.4.1 | PATCH | Ensure permissions on bootloader config are configured
  file:
    path: '{{ grub_cfg.stat.lnk_source }}'
    owner: root
    group: root
    mode: 384
  when:
    - grub_cfg.stat.exists and grub_cfg.stat.islnk
    - ubuntu1604cis_rule_1_4_1
  tags:
    - level1
    - scored
    - grub
    - patch
    - rule_1.4.1

- name: SCORED | 1.4.2 | PATCH | Ensure bootloader password is set
  grub_crypt:
    password: '{{ ubuntu1604cis_bootloader_password }}'
  register: grub_pass
  when:
    - ubuntu1604cis_set_boot_pass
    - ubuntu1604cis_rule_1_4_2
  tags:
    - level1
    - scored
    - grub
    - patch
    - rule_1.4.2

- name: SCORED | 1.4.2 | PATCH | Ensure bootloader password is set
  copy:
    dest: /etc/grub.d/01_password
    content: |
      set superusers="root"
      password_pbkdf2 root {{grub_pass}}
  notify: generate new grub config
  when:
    - ubuntu1604cis_set_boot_pass and grub_pass is defined and grub_pass.passhash is defined and grub_pass.passhash != ''
    - ubuntu1604cis_rule_1_4_2
  tags:
    - level1
    - scored
    - grub
    - patch
    - rule_1.4.2

- name: NOTSCORED | 1.4.3 | PATCH | Ensure authentication required for single user mode
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_4_3
  tags:
    - level1
    - level2
    - patch
    - rule_1.4.3
    - notimplemented

- name: NOTSCORED | 1.4.3 | PATCH | Ensure authentication required for single user mode
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_4_3
  tags:
    - level1
    - level2
    - patch
    - rule_1.4.3
    - notimplemented

- name: SCORED | 1.5.1 | PATCH | Ensure core dumps are restricted
  lineinfile:
    state: present
    dest: /etc/security/limits.conf
    regexp: '^#?\\*.*core'
    line: '*                hard    core            0'
    insertbefore: '^# End of file'
  when:
    - ubuntu1604cis_rule_1_5_1
  tags:
    - level1
    - scored
    - limits
    - patch
    - rule_1.5.1

- name: SCORED | 1.5.1 | PATCH | Ensure core dumps are restricted
  sysctl:
    name: fs.suid_dumpable
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
    - ubuntu1604cis_rule_1_5_1
  tags:
    - level1
    - scored
    - sysctl
    - patch
    - rule_1.5.1

- name: NOTSCORED | 1.5.2 | PATCH | Ensure XD/NX support is enabled
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_5_2
  tags:
    - level1
    - level2
    - patch
    - rule_1.5.2
    - notimplemented

- name: SCORED | 1.5.3 | PATCH | Ensure address space layout randomization (ASLR) is enabled
  sysctl:
    name: kernel.randomize_va_space
    value: 2
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
    - ubuntu1604cis_rule_1_5_3
  tags:
    - level1
    - scored
    - patch
    - rule_1.5.3

- name: SCORED | 1.5.4 | PATCH | Ensure prelink is disabled
  command: prelink -ua
  when:
    - prelink_installed.rc == 0
    - ubuntu1604cis_rule_1_5_4
  tags:
    - level1
    - scored
    - patch
    - rule_1.5.4

- name: SCORED | 1.5.4 | PATCH | Ensure prelink is disabled
  apt:
    name: prelink
    state: absent
  when:
    - ubuntu1604cis_rule_1_5_4
  tags:
    - level1
    - scored
    - patch
    - rule_1.5.4

- name: SCORED | 1.6.1.1 | PATCH | Ensure SELinux is not disabled in bootloader configuration
  replace:
    dest: /etc/default/grub
    regexp: (selinux|enforcing)\s*=\s*0\s*
    follow: yes
  register: selinux_grub_patch
  ignore_errors: yes
  notify: generate new grub config
  when:
    - ubuntu1604cis_rule_1_6_1_1
  tags:
    - level2
    - scored
    - patch
    - rule_1.6.1.1

- name: SCORED | 1.6.1.2 | PATCH | Ensure the SELinux state is enforcing
  selinux:
    conf: /etc/selinux/config
    policy: '{{ ubuntu1604cis_selinux_pol }}'
    state: enforcing
  when:
    - not ubuntu1604cis_selinux_disable
    - ubuntu1604cis_rule_1_6_1_2
  tags:
    - level2
    - scored
    - selinux
    - patch
    - rule_1.6.1.2

- name: SCORED | 1.6.1.3 | PATCH | Ensure SELinux policy is configured
  selinux:
    conf: /etc/selinux/config
    policy: '{{ ubuntu1604cis_selinux_pol }}'
    state: enforcing
  when:
    - not ubuntu1604cis_selinux_disable
    - ubuntu1604cis_rule_1_6_1_3
  tags:
    - level2
    - scored
    - selinux
    - patch
    - rule_1.6.1.3

- name: SCORED | 1.6.1.4 | PATCH | Ensure no unconfined daemons exist
  command: /bin/true
  changed_when: no
  when:
    - ubuntu1604cis_rule_1_6_1_4
  tags:
    - level2
    - scored
    - selinux
    - patch
    - rule_1.6.1.4
    - notimplemented

- name: SCORED | 1.6.2.1 | PATCH | Ensure AppArmor is not disabled in bootloader configuration
  replace:
    dest: /etc/default/grub
    regexp: apparmor\s*=\s*0\s*
    follow: yes
  register: apparmor_grub_patch
  ignore_errors: yes
  notify: generate new grub config
  when:
    - ubuntu1604cis_rule_1_6_2_1
  tags:
    - level2
    - scored
    - patch
    - rule_1.6.2.1

- name: SCORED | 1.6.3 | PATCH | Ensure SELinux or AppArmor are installed
  apt:
    name: apparmor
    state: present
  when:
    - ubuntu1604cis_rule_1_6_3
  tags:
    - level2
    - scored
    - patch
    - rule_1.6.3

- name: SCORED | 1.7.1.1 | PATCH | Ensure message of the day is configured properly
  template:
    src: etc/motd.j2
    dest: /etc/motd
  when:
    - ubuntu1604cis_rule_1_7_1_1
  tags:
    - level1
    - banner
    - patch
    - rule_1.7.1.1

- name: NOTSCORED | 1.7.1.2 | PATCH | Ensure local login warning banner is configured properly
  template:
    src: etc/issue.j2
    dest: /etc/issue
  when:
    - ubuntu1604cis_rule_1_7_1_2
  tags:
    - level1
    - patch
    - rule_1.7.1.2

- name: NOTSCORED | 1.7.1.3 | PATCH | Ensure remote login warning banner is configured properly
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
  when:
    - ubuntu1604cis_rule_1_7_1_3
  tags:
    - level1
    - banner
    - patch
    - rule_1.7.1.3

- name: NOTSCORED | 1.7.1.4 | PATCH | Ensure permissions on /etc/motd are configured
  file:
    dest: /etc/motd
    state: file
    owner: root
    group: root
    mode: 420
  when:
    - ubuntu1604cis_rule_1_7_1_4
  tags:
    - level1
    - perms
    - patch
    - rule_1.7.1.4

- name: SCORED | 1.7.1.5 | PATCH | Ensure permissions on /etc/issue are configured
  file:
    dest: /etc/issue
    state: file
    owner: root
    group: root
    mode: 420
  when:
    - ubuntu1604cis_rule_1_7_1_5
  tags:
    - level1
    - perms
    - patch
    - rule_1.7.1.5

- name: NOTSCORED | 1.7.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured
  file:
    dest: /etc/issue.net
    state: file
    owner: root
    group: root
    mode: 420
  when:
    - ubuntu1604cis_rule_1_7_1_6
  tags:
    - level1
    - perms
    - patch
    - rule_1.7.1.6

- name: SCORED | 1.7.2 | PATCH | Ensure GDM login banner is configured
  lineinfile:
    dest: '{{ item.file }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    create: yes
    owner: root
    group: root
    mode: 420
  with_items:
    - file: /etc/dconf/profile/gdm
      regexp: user-db
      line: 'user-db:user'
    - file: /etc/dconf/profile/gdm
      regexp: system-db
      line: 'system-db:gdm'
    - file: /etc/dconf/profile/gdm
      regexp: file-db
      line: 'file-db:/usr/share/gdm/greeter-dconf-defaults'
    - file: /etc/dconf/db/gdm.d/01-banner-message
      regexp: '\[org\/gnome\/login-screen\]'
      line: '[org/gnome/login-screen]'
    - file: /etc/dconf/db/gdm.d/01-banner-message
      regexp: banner-message-enable
      line: banner-message-enable=true
    - file: /etc/dconf/db/gdm.d/01-banner-message
      regexp: banner-message-text
      line: 'banner-message-text=''{{ ubuntu1604cis_warning_banner }}'' '
  when:
    - ubuntu1604cis_gui
    - ubuntu1604cis_rule_1_7_2
  tags:
    - level1
    - level2
    - patch
    - rule_1.7.2

- name: NOTSCORED | 1.8 | PATCH | Ensure updates, patches, and additional security software are installed
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - level1
    - level2
    - patch
    - rule_1.8
